###################
#MINIMUM STUDY DURATION #
###################

#LOAD PACKAGES
require(manipulate)
require(Hmisc)

# THE DATA FRAMES INCLUDES A VARIABLE CALLED "INTERVAL" . THIS IS THE NUMBER OF DAYS BETWEEN TWO CONSECUTIVE
#OBSERVATIONS OF THE SAME TYPE, I.E. PRESENCE, OR REST. INTERVALS AFFECTED BY GAPS CAUSED BY CAMERA MALFUNCTION HAVE BEEN EXCLUDED. 
 

#TO INVESTIGATE PRESENCE, I.E. ALL REGISTRATIONS READ IN C_STUDY_DURATION_PRESENCE.
#TO INVESTIGATE RESTS, READ IN C_STUDY_DURATION_REST

main<-read.csv("C_STUDY_DURATION_PRESENCE.csv")
main2<-read.csv("C_STUDY_DURATION_REST.csv")

#LOAD PACKAGE
require(lme4)

#TEST FOR ANY RELATIONSHIP BETWEEN INTERVALS IN DAYS AND PRESENCE
#CREATE MODEL
model<-glm(main$INTERVAL~main$FUNCTION,family=poisson)

anova(model,test="Chi")

#TEST FOR ANY RELATIONSHIP BETWEEN INTERVALS IN DAYS AND RESTS
model2<-glm(main2$INTERVAL~main2$FUNCTION,family=poisson)

#EXTRACT PARAMETER ESTIMATES
summary(model) 
summary(model2)

